### ISSUE TITLE
what is the performance result?which is fastest

### ISSUE THREAD

**Issue by V0idk** [harawata/mybatis-bulk-insert#6]

**Comment by harawata** [comment]
This project is a demo for the blog post entry.
https://blog.harawata.net/2016/04/bulk-insert-multi-row-vs-batch-using.html
I need to update the example to using JMH, but haven't found the time for it.

If you have to process many rows, I recommend using batch executor.

If you have difficulty, ask it on https://stackoverflow.com/questions/ask?tags=mybatis.
I may be able to help _if_ I could reproduce the problem.
